export {default as Login} from './Login/Login'
export {default as Home} from './Home/Home'
export {default as Public} from './Public/Public'
export {default as Screeningform} from './Screeningform/Screeningform'
export {default as Statistical} from './statistical/Statistical'
export {default as PrintReport} from './Report/PrintReport'